# Lab2 - PyTorch Assignment

In [1]:
import torch
import torch.nn.functional as F
print(torch.__version__)

1.1.0


## Question 1
Create a tensor(1*40) with elements from 10 to 49.

Print out its max element and minim element. (hint: The more concise, the higher the score)

**Reference answer:**
```
tensor([10., 11., 12., 13., 14., 15., 16., 17., 18.,
19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40.,
41., 42., 43., 44., 45., 46., 47., 48., 49.])
tensor(49.)
tensor(10.)
```

In [2]:
x = torch.arange(10,50)
print(x.max())
print(x.min())

tensor(49)
tensor(10)


## Question 2

Define two matrix (arbitrary size), use the small matrix to silde on the big matrix from left to right and from up to down. At each step, we multiply the corresponding elements of the two matrices and add the result of mutiplying. Finally, we use all elements we get to create a new matrix. Please print out the matrix.

![cov](fig/conv.gif)

In [3]:
x = torch.rand((5,5))
kernel = torch.rand((3,3))
print(x)
print(kernel)
out = torch.zeros((3,3))
for i in range(0,3):
    for j in range(0,3):
        out[i,j] = (x[i:i+3,j:j+3] * kernel).sum() # element-wise multiplication
print(out)

# use inherent method
x = x.unsqueeze(0).unsqueeze(0)
kernel = kernel.unsqueeze(0).unsqueeze(0)
print(F.conv2d(x,kernel).squeeze(0).squeeze(0))

tensor([[0.5334, 0.5025, 0.0239, 0.1276, 0.3992],
        [0.4595, 0.3946, 0.7182, 0.7755, 0.0490],
        [0.6403, 0.3052, 0.0022, 0.6717, 0.9881],
        [0.0481, 0.3205, 0.7136, 0.2080, 0.1687],
        [0.5168, 0.8023, 0.6032, 0.5407, 0.5032]])
tensor([[0.1765, 0.9772, 0.8787],
        [0.8639, 0.5087, 0.6529],
        [0.3107, 0.0684, 0.9341]])
tensor([[1.8947, 2.1590, 2.4963],
        [2.5111, 2.4990, 2.3099],
        [1.8626, 2.2176, 3.0519]])
tensor([[1.8947, 2.1590, 2.4963],
        [2.5111, 2.4990, 2.3099],
        [1.8626, 2.2176, 3.0519]])
